// Phase 4G-A: Azure Database for PostgreSQL Flexible Server -- pilot-
// appropriate burstable configuration, single-zone, 32 GiB initial
// storage, TLS enforced, private access only (no public network access,
// task 9's explicit requirement). Storage auto-grow is explicitly
// disabled: task 9 requires "Do not enable storage auto-growth without
// an explicit tested upper bound; if Azure cannot enforce one, leave
// auto-growth disabled and add storage alerts" -- Azure's own
// auto-grow feature has no configurable upper bound, only an on/off
// switch, so it is left off here; `monitoring.bicep` adds a storage-
// percent-used alert instead.
//
// **Administrator credential**: the server's own administrator login is
// provisioned with a Bicep-generated, never-retained password (task 4's
// privilege-separation intent) -- this module never outputs it, and it
// is never intended for application runtime use. The application's own
// runtime/migration/operator roles are documented, not created by this
// module (native PostgreSQL role/GRANT management is not a Bicep-
// expressible resource) -- see `docs/deployment/
// azure-ingestion-production.md`'s own provisioning-checklist section
// for the exact `CREATE ROLE`/`GRANT` statements an operator must run
// once, out of band, after this server is created.

@description('Azure region. Must be canadacentral.')
param location string = 'canadacentral'

@description('Server name (globally unique within the region).')
param serverName string

@description('Tags applied to every resource this module creates.')
param tags object

@description('Subnet resource ID delegated to Microsoft.DBforPostgreSQL/flexibleServers.')
param delegatedSubnetId string

@description('VNet resource ID, for the private-DNS-zone virtual network link.')
param vnetId string

@description('Administrator login name.')
param administratorLogin string = 'cogadmin'

@secure()
@description('Administrator password -- generated by the caller (main.bicep) at deployment time, never a checked-in value.')
param administratorPassword string

@description('Burstable SKU name -- pilot-scale default (Recorded human decisions: target ~CAD $42-70/month ordinary spend).')
param skuName string = 'Standard_B1ms'

@description('Initial storage size in GiB.')
param storageSizeGB int = 32

@description('PostgreSQL major version.')
param postgresVersion string = '16'

resource privateDnsZone 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: '${serverName}.private.postgres.database.azure.com'
  location: 'global'
  tags: tags
}

resource privateDnsZoneLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: privateDnsZone
  name: '${serverName}-link'
  location: 'global'
  properties: {
    registrationEnabled: false
    virtualNetwork: {
      id: vnetId
    }
  }
}

resource postgresServer 'Microsoft.DBforPostgreSQL/flexibleServers@2024-08-01' = {
  name: serverName
  location: location
  tags: tags
  sku: {
    name: skuName
    tier: 'Burstable'
  }
  properties: {
    version: postgresVersion
    administratorLogin: administratorLogin
    administratorLoginPassword: administratorPassword
    network: {
      delegatedSubnetResourceId: delegatedSubnetId
      privateDnsZoneArmResourceId: privateDnsZone.id
    }
    storage: {
      storageSizeGB: storageSizeGB
      autoGrow: 'Disabled' // No unbounded auto-growth (task 9) -- monitoring.bicep alerts on percent-used instead.
    }
    backup: {
      backupRetentionDays: 7 // Recorded human decision: initial target seven-day rotation.
      geoRedundantBackup: 'Disabled' // No cross-region database backup (task 9's explicit requirement).
    }
    highAvailability: {
      mode: 'Disabled' // Single-zone, pilot-scale (Recorded human decisions).
    }
  }
  dependsOn: [
    privateDnsZoneLink
  ]
}

// TLS enforcement is PostgreSQL Flexible Server's own default
// (`require_secure_transport = ON`) and is not disabled anywhere in this
// module -- no `require_secure_transport` server parameter override is
// set here, which would be the only way to weaken it.

output serverId string = postgresServer.id
output fullyQualifiedDomainName string = postgresServer.properties.fullyQualifiedDomainName
