// Phase 4G-A: foundation deployment -- every resource that must exist
// *before* an OCI image can be built, pushed, and referenced by digest
// (task 9's explicit "split foundation and application modules"
// requirement). Deployed first; `app.bicep` is deployed second, once a
// real image digest exists.
//
// **This template creates no resource by itself in this pass** -- Phase
// 4G-A only authors and locally validates (`bicep build`) this
// infrastructure-as-code; deploying it is Phase 4G-B, separately
// authorized, work.

targetScope = 'resourceGroup'

@description('Azure region. Hard-coded to canadacentral -- every data-bearing resource in this deployment must live in this exact region (Recorded human decision); no parameter overrides this.')
var location = 'canadacentral'

@description('Resource name prefix, e.g. cog-ingestion-pilot.')
param namePrefix string

@description('Globally-unique suffix (e.g. a short random string) appended to globally-unique resource names (storage account, ACR, Key Vault) to avoid collisions with other subscriptions.')
param globalSuffix string

@description('Azure AD tenant ID, for Key Vault RBAC.')
param tenantId string

@secure()
@description('PostgreSQL Flexible Server administrator password -- generated by the deployer at deployment time (e.g. `az postgres flexible-server` password-generation guidance), never a checked-in or default value.')
param postgresAdministratorPassword string

@description('Budget start date -- must be the first day of the *current* calendar month at deployment time (correction-pass item 10). No default: see modules/budget.bicep\'s own parameter description for why a checked-in default is never safe here.')
param budgetStartDate string

@description('Correction pass, item 4: whether to also deploy `keyvault-secret-rbac.bicep`, granting each identity read access to its own Key Vault secrets. Left at its default (false) for the first foundation deployment (which creates the vault and identities only, with no secret and no per-secret RBAC) -- an operator then creates all eight real secret values out of band (`docs/deployment/azure-ingestion-production.md` §9), after which foundation.bicep is deployed again with this set to true. Bicep itself never creates, writes, or is capable of writing a Key Vault secret value anywhere in this template -- see keyvault.bicep\'s own header comment for the complete three-stage bootstrap.')
param assignKeyVaultSecretRbac bool = false

@description('Deterministic tags applied to every resource -- identify project, environment, residency, data classification, and IaC ownership (task 9\'s explicit requirement).')
var tags = {
  project: 'cloudops-guard-ingestion-api'
  environment: 'pilot'
  dataResidency: 'canada-central'
  dataClassification: 'customer-report-metadata'
  managedBy: 'bicep-infra-azure'
  phase: '4g-a-foundation'
}

module network 'modules/network.bicep' = {
  name: 'network'
  params: {
    location: location
    namePrefix: namePrefix
    tags: tags
  }
}

module logAnalytics 'modules/log-analytics.bicep' = {
  name: 'log-analytics'
  params: {
    location: location
    namePrefix: namePrefix
    tags: tags
  }
}

module containerRegistry 'modules/container-registry.bicep' = {
  name: 'container-registry'
  params: {
    location: location
    registryName: '${replace(namePrefix, '-', '')}acr${globalSuffix}'
    tags: tags
  }
}

module storage 'modules/storage.bicep' = {
  name: 'storage'
  params: {
    location: location
    storageAccountName: '${replace(namePrefix, '-', '')}st${globalSuffix}'
    tags: tags
    vnetId: network.outputs.vnetId
    privateEndpointSubnetId: network.outputs.privateEndpointsSubnetId
  }
}

module postgresql 'modules/postgresql.bicep' = {
  name: 'postgresql'
  params: {
    location: location
    serverName: '${namePrefix}-pg-${globalSuffix}'
    tags: tags
    delegatedSubnetId: network.outputs.postgresSubnetId
    vnetId: network.outputs.vnetId
    administratorPassword: postgresAdministratorPassword
  }
}

module keyVault 'modules/keyvault.bicep' = {
  name: 'keyvault'
  params: {
    location: location
    keyVaultName: '${replace(namePrefix, '-', '')}kv${globalSuffix}'
    tags: tags
    tenantId: tenantId
    vnetId: network.outputs.vnetId
    privateEndpointSubnetId: network.outputs.privateEndpointsSubnetId
  }
}

module managedIdentities 'modules/managed-identities.bicep' = {
  name: 'managed-identities'
  params: {
    location: location
    namePrefix: namePrefix
    tags: tags
    containerRegistryName: containerRegistry.outputs.registryName
    storageAccountName: storage.outputs.storageAccountName
    reportContainerName: storage.outputs.reportContainerName
  }
}

// Correction pass, item 4, stage 3 of the bootstrap: grants each
// identity read access to its own Key Vault secrets, but only once an
// operator has confirmed every real secret value already exists (stage
// 2, out of band) -- left undeployed (the default) on the first
// foundation deployment, which creates the vault and identities with no
// secret and no per-secret RBAC assignment.
module keyVaultSecretRbac 'modules/keyvault-secret-rbac.bicep' = if (assignKeyVaultSecretRbac) {
  name: 'keyvault-secret-rbac'
  params: {
    keyVaultName: keyVault.outputs.keyVaultName
    appIdentityPrincipalId: managedIdentities.outputs.appIdentityPrincipalId
    operatorIdentityPrincipalId: managedIdentities.outputs.operatorIdentityPrincipalId
    migrationIdentityPrincipalId: managedIdentities.outputs.migrationIdentityPrincipalId
  }
}

module containerAppsEnvironment 'modules/container-apps-environment.bicep' = {
  name: 'container-apps-environment'
  params: {
    location: location
    namePrefix: namePrefix
    tags: tags
    delegatedSubnetId: network.outputs.containerAppsSubnetId
    logAnalyticsCustomerId: logAnalytics.outputs.customerId
    logAnalyticsWorkspaceName: logAnalytics.outputs.workspaceName
  }
}

module budget 'modules/budget.bicep' = {
  name: 'budget'
  params: {
    budgetName: '${namePrefix}-budget'
    startDate: budgetStartDate
  }
}

output registryLoginServer string = containerRegistry.outputs.loginServer
output environmentId string = containerAppsEnvironment.outputs.environmentId
output keyVaultUri string = keyVault.outputs.keyVaultUri
output postgresFqdn string = postgresql.outputs.fullyQualifiedDomainName
output blobEndpoint string = storage.outputs.blobEndpoint
output reportContainerName string = storage.outputs.reportContainerName
output appIdentityId string = managedIdentities.outputs.appIdentityId
output appIdentityClientId string = managedIdentities.outputs.appIdentityClientId
output migrationIdentityId string = managedIdentities.outputs.migrationIdentityId
output migrationIdentityClientId string = managedIdentities.outputs.migrationIdentityClientId
output operatorIdentityId string = managedIdentities.outputs.operatorIdentityId
output operatorIdentityClientId string = managedIdentities.outputs.operatorIdentityClientId
output postgresServerId string = postgresql.outputs.serverId
